name: Vue.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    # CHÚ Ý: Đổi tên thư mục dưới đây cho đúng với thư mục chứa code Vue của bạn
    defaults:
      run:
        working-directory: ./e-learning-frontend 

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Cài đặt môi trường Node.js
        cache: 'npm'
        cache-dependency-path: ./e-learning-frontend/package-lock.json # Lưu cache để lần sau chạy nhanh hơn

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: npm run build

    # Nếu project Vue của bạn có dùng ESLint để check lỗi code, hãy bỏ dấu # ở 2 dòng dưới
    # - name: Run Linter
    #   run: npm run lint
